# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@name Cauchy_marginal
#'@title Marginal likelihood of Cauchy prior
NULL

#'@return marginal likelihood 
NULL

Cauchy_marginal <- function(index_vec_input, Sigma, z, zSigmaz, tau, p, p_S) {
    .Call(`_CARMA_Cauchy_marginal`, index_vec_input, Sigma, z, zSigmaz, tau, p, p_S)
}

#'@name Cauchy_fixed_sigma_marginal
#'@title Marginal likelihood of Cauchy prior when varinace is fixed
NULL

#'@return marginal likelihood
NULL

Cauchy_fixed_sigma_marginal <- function(index_vec_input, Sigma, z, tau, p_S, y_sigma) {
    .Call(`_CARMA_Cauchy_fixed_sigma_marginal`, index_vec_input, Sigma, z, tau, p_S, y_sigma)
}

#'@name hyper_g_marginal
#'@title Marginal likelihood of hyper-g prior
NULL

#'@return marginal likelihood
NULL

hyper_g_marginal <- function(index_vec_input, Sigma, z, zSigmaz, p, tau, p_S) {
    .Call(`_CARMA_hyper_g_marginal`, index_vec_input, Sigma, z, zSigmaz, p, tau, p_S)
}

#'@name hyper_g_fixed_sigma_marginal
#'@title Marginal likelihood of hyper-g prior when varinace is fixed
NULL

#'@return marginal likelihood
NULL

hyper_g_fixed_sigma_marginal <- function(index_vec_input, Sigma, z, tau, p_S, y_sigma) {
    .Call(`_CARMA_hyper_g_fixed_sigma_marginal`, index_vec_input, Sigma, z, tau, p_S, y_sigma)
}

#'@name Normal_marginal
#'@title Marginal likelihood of Normal prior
NULL

#'@return marginal likelihood
NULL

Normal_marginal <- function(index_vec_input, Sigma, z, zSigmaz, tau, p, p_S) {
    .Call(`_CARMA_Normal_marginal`, index_vec_input, Sigma, z, zSigmaz, tau, p, p_S)
}

#'@name Normal_fixed_sigma_marginal
#'@title Marginal likelihood of Normal prior when varinace is fixed
NULL

#'@return marginal likelihood
NULL

Normal_fixed_sigma_marginal <- function(index_vec_input, Sigma, z, tau, p_S, y_sigma) {
    .Call(`_CARMA_Normal_fixed_sigma_marginal`, index_vec_input, Sigma, z, tau, p_S, y_sigma)
}

